import type { Metadata } from "next";
import "./globals.css";
import { font } from "@/lib/cores/constants/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={font.variable}>
      <body className={`font-manrope antialiased bg-black2 text-white1`}>
        {children}
      </body>
    </html>
  );
}
