import type { Metadata } from "next";
import "./globals.css";
import { font } from "@/lib/cores/constants/fonts";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Providers } from "@/lib/cores/providers/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={font.variable}>
      <body className={`font-manrope antialiased bg-black2 text-white1`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
